name: Build

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, osx-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - run: dotnet publish --configuration Release src/WhereEsolang.Cli
      - uses: actions/upload-artifact@v4
        with:
          name: whereso-${{ matrix.os }}
          path: src/WhereEsolang.Cli/bin/Release/net*/*/publish/WhereEsolang.Cli

